great_expectations_provider/operators/great_expectations.py

Makes checkpoint name templateable. This makes it a lot easier to e.g. validate against staging table using airflow macros.
E.g when you have a daily generated staging table test_staging_tbl_201123 that you want to validate that against you can just specify the query in you checkpoint to use test_staging_tb_{{ ds_nodash }}

Template checkpoints

---

great_expectations_provider/operators/great_expectations.py

fixes #3
Alternatively, we can return text from the "callback" to the Airflow Exception, or just internalize bullet-generation

pass fail callback function

---

great_expectations_provider/operators/great_expectations.py

The bug is that jinja template fields like `batch_kwargs` don't render. The fix is to make `template_fields` on line 33  a tuple instead of a list.
I'm not sure why though. The airflow [docs ](https://airflow.apache.org/docs/apache-airflow/2.0.0/howto/custom-operator.html#templating) clearly use a list.
However a tuple makes everything work great on my 2.0.0-2 airflow version. Also, other [provider packages](https://github.com/apache/airflow/blob/master/airflow/providers/amazon/aws/operators/athena.py) I've tested successfully use tuples for the `template_fields` as well.

[BUGFIX] jinja template fields not rendering

---

great_expectations_provider/operators/great_expectations.py
great_expectations_provider/operators/great_expectations_bigquery.py

Hi @spbail.  This pull request is adding the GE Bigquery operator that extends the GE base operator.  The only change to the base operator is that the execute method returns the results at the end so the bigquery operator can examine the results to determine success or failure and and use them to get a data docs link.  I did a functional test and it worked fine using GE 0.13.1 and Cloud Composer version composer-1.11.3-airflow-1.10.6.  I'll still working on unit tests.

adding ge bigquery operator

---

CHANGELOG.md
README.md
great_expectations_provider/operators/great_expectations.py
requirements.txt

As of Great Expectations v0.13.8, we use SimpleCheckpoints instead of the former ValidationOperators. This PR updates the airflow-provider-great-expectations to reflect this change.

[BUGFIX] Update operator to work with Checkpoints

---

great_expectations_provider/operators/great_expectations.py

An extra space in this docstring is causing an error with sphinx doc builder parser

fixed docstring

---

great_expectations_provider/operators/great_expectations_bigquery.py

This PR fixes a bug whereby the `fail_task_on_validation_failure` in the BigQuery operator was being shadowed by the parent class.

[BUGFIX] Fix fail_task_on_validation argument overwriting

---

great_expectations_provider/operators/great_expectations.py

This fixes an issue whereby the GreatExpectationsOperator is triggering a LegacyCheckpoint  but without `validation_operator_name` which is necessary for Slack notifications.
Closes #30

Add support for validation operators in LegacyCheckpoints

---

README.md

link to greatexpectations.io was broken in README. fixed it to point to https://greatexpectations.io/

Fix broken greatexpectations.io link in README

---

CHANGELOG.md
setup.py
tests/operators/test_great_expectations.py

Astronomer's docker image is using an epoch version, which seems to break against the maximum version on the GE side. 
The Docker image uses `apache-airflow==1!2.2.3+astro.1`. The `1!` is the epoch which makes all the versioning "greater" than any non-epoch'd version. As per https://www.python.org/dev/peps/pep-0440/#version-epochs, any version without a specified epoch has an epoch of `0`. So 1!2.2.3 > 0!3.0 with creates an impossible dependency loop (and an upper constraint of 1!3.0 would be ostensibly useless).
This PR removes this upper bound, and also removes a test which was failing, and wasn't needed to begin with.

[BUGFIX] Resolve dependency issue with Astronomer Docker container

---

CHANGELOG.md
great_expectations_provider/operators/great_expectations.py
setup.py
tests/operators/test_great_expectations.py

Due to changes to the signature of the Checkpoint class, an error was being thrown when instantiating a Checkpoint from a Checkpoint Config. This PR updates the method of instantiation to use `instantiate_class_from_config` which is a more appropriate means of doing this.
It also contains changes necessary for the release of a new version.

[BUGFIX] Fix error with the instantiation of a Checkpoint from a CheckpointConfig

---

great_expectations_provider/operators/great_expectations.py

Moved the data context and checkpoint initializations
from the __init__() method to the execute() method of
the operator. Because an operator's __init__() is called
every time a DAG is parsed, the data context was being
created on every parse, slowing down the DAGs this operator
was in significantly. This change ensures that the data
context is only created during operator execution, when
it is needed.
Signed-off-by: Benji Lampel <benjamin@astronomer.io>

Improve Performance of GreatExpectationsOperator

---

CHANGELOG.md
setup.py
tests/operators/test_great_expectations.py

This fixes a couple of tests that were broken as a result of changes to the core library and to the operator, and also prepares for the coming release.

[MAINTENANCE] Fix tests and prep release for 0.1.3

---

CHANGELOG.md
setup.py

This removes the pin for sqlalchemy to support later versions of apache-airflow. It also preps for a new release.

[MAINTENANCE] Remove upper pin of sqlalchemy and prep for release

---

CHANGELOG.md
great_expectations_provider/operators/great_expectations.py
setup.py
tests/operators/test_great_expectations.py

Adds in template fields for:
- `run_name`
- `conn_id`
- `data_context_root_dir`
- `checkpoint_name`
- `checkpoint_kwargs`

Add back in template fields for new operator

---

great_expectations_provider/operators/great_expectations.py
tests/operators/test_great_expectations.py

Adds a comma to the end of the template_ext set, making the quoted '.sql' a member of the set, not each character in the string a member of the set. This was breaking jinja templating. Testing has been updated to ensure the whole value, not the characters, of the elements of the template_ext set are present.

Fix template extension bug

---

setup.cfg

Hi @denimalpaca,  I realized that our operator is installing `great-expectations 0.13.x ` (published on 3/17/2021) and the latest `great-expectations 0.15.x `has a lot of updates and bug fixes. 
I believe some issues related to `data_asset_name` can be resolved if we keep with the latest version of `great-expectations`
Reference: https://github.com/great-expectations/great_expectations/issues/6260
Let me know if you have any opinions and feel free to let me know what is our best practice for adding test cases.
Look forward to hearing back from you.
Thanks,

upgraded great-expectations>=0.15.34 and sqlalchemy>=1.4.44

---

great_expectations_provider/operators/great_expectations.py
tests/operators/test_great_expectations.py

A new schema parameter will overwrite the supplied connection's schema, if it exists. If a data_asset_name is provided in the form 'schema.table', the schema will be parsed out into self.schema and data_asset_name will be updated to only be the table. This will also override the supplied schema in the connection.
Closes: #74

Add schema parameter and data_asset_name parsing

---

great_expectations_provider/operators/great_expectations.py
tests/operators/test_great_expectations.py

self.conn.schema was still being used in build_configured_sql_datasource_config_from_conn_id, which meant that the schema override for parameters was not happening in actuality as the datasource was still being built with the connection schema.

Bugfix connections override

---

great_expectations_provider/operators/great_expectations.py

An extraneous ValueError was in build_runtime_datasources and caused incorrect operator failure when a runtime datasource is built but a connection or dataframe is not passed in. The if/elif/else block would hit the else, which was a ValueError, and it made the below if statement on checkpoint_kwargs unreachable. It has been removed as the ValueError in the first if block is sufficient to halt operator execution in the case of incorrect usage.

[Bugfix] Remove unnecessary ValueError

---

great_expectations_provider/operators/great_expectations.py

Fixes #83 . 
Snowflake provider 4.0.0 changed the kwargs generated when the connection is defined in the Airflow UI. I left the old kwargs as a fallback.

Change kwargs in Snowflake URI generation

---

great_expectations_provider/operators/great_expectations.py
tests/operators/test_great_expectations.py

This adds support for Snowflake key based auth, see: https://docs.snowflake.com/en/user-guide/sqlalchemy.html#key-pair-authentication-support

Snowflake key auth

---

great_expectations_provider/operators/great_expectations.py
setup.cfg
tests/operators/test_great_expectations.py

This change uses the SnowflakeHook from the `airflow.providers.snowflake.hooks.snowflake` module to build the connection string.
Great Expectations expects a different configuration structure for a datasource that uses Snowflake and private key authentication. PR #93 does not cover all possible ways a Snowflake connection can be configured in Airflow.
I thought it would be best to optionally rely on the Snowflake provider package and fall back to the existing functionality if the provider package is not available (tho I doubt anyone would use Snowflake without the provider package)
Instead of using the `SnowflakeHook`, I could duplicate the behaviour from the hook into the GE Operator? It is up to the maintainer imho.
Please let me know if you have any questions/concerns or would like me …

Use Snowflake provider to build connection string

---

great_expectations_provider/operators/great_expectations.py

Snowflake Region Should be Optional

---

include/great_expectations/plugins/expectations/expect_column_values_to_be_alphabetical.py

Hey there! I'm a core dev on the GX team and am currently working through cleaning up some deprecated code as part of our v16 release.
One of these items happens to be the `great_expectations.expectations.metrics.map_metric` import - this has been renamed to `great_expectations.expectations.metrics.map_metric_provider` as of v0.13 and per our policy of removing deprecated code after two minor versions, I'm hoping to delete as much old code as possible.
I've proposed the necessary change below. Thanks!

Update deprecated map_metric import in custom 

---

great_expectations_provider/operators/great_expectations.py
tests/operators/test_great_expectations.py

Add an Athena URI builder to make_connection_string(), assuming for now that Athena is the only connection when an AWS connection type is given. This is an incorrect assumption, but we currently do not have asks for other use cases figuring out how to differentiate these may be a non-trivial issue.
Closes: #90

Add Athena Connection Support

---

great_expectations_provider/operators/great_expectations.py
tests/operators/test_great_expectations.py

Hi :) 
This came up in the GX Slack twice. Using the GXO with a MSSQL conn_id currently does not work because there is no driver being passed via the URI. If fails with:
```
sqlalchemy.exc.InterfaceError: (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
```
There was also an issue with the connection needing a database argument separate from the schema passed through the operator.
This PR should fix that. I added the possibility to pass a driver via the connection extras, if none is passed `ODBC Driver 17 for SQL Server` is passed, which is what worked for me when testing with the `mcr.microsoft.com/mssql/server:2022-latest` image. 
I tested this change with Postgres and MSSQL. …

Fix make_connection_configuration for MSSQL (adding a driver)

---

great_expectations_provider/operators/great_expectations.py
tests/operators/test_great_expectations.py

Allows users to configure `create_temp_table` by using the `extra` field in the connection form. The value of `create_temp_table` is `true` by default and, by setting it to `false`, it bypasses the creation of temporary tables from Great Expectations. Which is necessary when one only has read access to a database.
Usage:
In the `extras` field do the following:
{
"create_temp_table": false
}

add create_temp_table support

---

great_expectations_provider/operators/great_expectations.py
tests/operators/test_great_expectations.py

There was a requirement in the work I am doing to dynamically set the `schema` property from a REST API request. So I am adding `schema` as a template field so it can be set using `params`.

add schema as a template field

---

setup.cfg

airflow-provider-great-expectations is not compatible with great_expectations 1.0.0
Closes #148
airflow-provider-great-expectations is not compatible with great_expectations 1.0.0
CheckpointResult has been removed so the following import is currently failing!
from great_expectations.checkpoint.types.checkpoint_result import **CheckpointResult**
https://github.com/astronomer/airflow-provider-great-expectations/blob/main/great_expectations_provider/operators/great_expectations.py#L30
great-expectations PR that made the changes: https://github.com/great-expectations/great_expectations/pull/9824

Fix #148 compatibility issue  with great_expectations 1.0.0

---

great_expectations_provider/operators/great_expectations.py
tests/operators/test_great_expectations.py

Since we’re preparing a release to include support for GX Core 1.0 and plan to remove existing operators in an upcoming release (as part of the work in PR #161), this PR adds a deprecation warning for the current operators.
related: #166

Add deprecation warnings for existing operators

---

docs/contributing/contributors.md

This PR adds the following contributors as committers as per the docs mentioned at https://github.com/astronomer/airflow-provider-great-expectations/blob/main/docs/contributing/contributor-roles.md#committers:
* Pankaj Koti ([@pankajkoti](https://github.com/pankajkoti))
* Joshua Stauffer ([@joshua-stauffer](https://github.com/joshua-stauffer))
* Tyler Hoffman ([@tyler-hoffman](https://github.com/tyler-hoffman))

Mention Committers in the documentation

---

README.md
docs/contributing/contributing-guide.md
docs/contributing/contributor-roles.md
docs/contributing/contributors.md
docs/index.md
docs/migration-guide.md

As we continue working on [Issue #181](https://github.com/astronomer/airflow-provider-great-expectations/issues/181), it would be beneficial to fix the broken URLs currently present on [PyPI](https://pypi.org/project/airflow-provider-great-expectations/1.0.0a1/). This ensures that the URLs function correctly in the upcoming alpha release, in case we are unable to complete Issue #181 in time.
Closes: #177

Use absolute GitHub URLs in the documentation

---

.pre-commit-config.yaml

Apparently PR #189 was created earlier when we had the setup.cfg file and looks like it is picking up invalid project configuration to run tests in CI and hence failing. I have created a this new PR using a branch cut from latest main that replicates the upgrade being attempted in #189 .

Upgrade pre-commit hook version as being attempted by pre-commit bot in PR #189

---

.github/workflows/zizmor.yml

Adds an automated security analysis workflow that runs the Zizmor scanner on every push to main and on all pull requests.
related: https://github.com/astronomer/oss-integrations-private/issues/156
Reference: https://docs.zizmor.sh/

Add Zizmor analysis GitHub action
